// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// allele_diff_strings
std::vector<std::string> allele_diff_strings(std::vector<std::string> germs, int X, Rcpp::Nullable<Rcpp::CharacterVector> non_mismatch_chars_nullable);
RcppExport SEXP _piglet_allele_diff_strings(SEXP germsSEXP, SEXP XSEXP, SEXP non_mismatch_chars_nullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type germs(germsSEXP);
    Rcpp::traits::input_parameter< int >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type non_mismatch_chars_nullable(non_mismatch_chars_nullableSEXP);
    rcpp_result_gen = Rcpp::wrap(allele_diff_strings(germs, X, non_mismatch_chars_nullable));
    return rcpp_result_gen;
END_RCPP
}
// allele_diff_indices
std::vector<int> allele_diff_indices(std::vector<std::string> germs, int X, Rcpp::Nullable<Rcpp::CharacterVector> non_mismatch_chars_nullable);
RcppExport SEXP _piglet_allele_diff_indices(SEXP germsSEXP, SEXP XSEXP, SEXP non_mismatch_chars_nullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type germs(germsSEXP);
    Rcpp::traits::input_parameter< int >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type non_mismatch_chars_nullable(non_mismatch_chars_nullableSEXP);
    rcpp_result_gen = Rcpp::wrap(allele_diff_indices(germs, X, non_mismatch_chars_nullable));
    return rcpp_result_gen;
END_RCPP
}
// allele_diff_paired
Rcpp::RObject allele_diff_paired(std::vector<std::string> germs, std::vector<std::string> inputs, int X, bool return_count, Rcpp::Nullable<Rcpp::CharacterVector> non_mismatch_chars_nullable);
RcppExport SEXP _piglet_allele_diff_paired(SEXP germsSEXP, SEXP inputsSEXP, SEXP XSEXP, SEXP return_countSEXP, SEXP non_mismatch_chars_nullableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type germs(germsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< int >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type return_count(return_countSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type non_mismatch_chars_nullable(non_mismatch_chars_nullableSEXP);
    rcpp_result_gen = Rcpp::wrap(allele_diff_paired(germs, inputs, X, return_count, non_mismatch_chars_nullable));
    return rcpp_result_gen;
END_RCPP
}
// insert_gaps
std::vector<std::string> insert_gaps(const std::vector<std::string>& gapped, const std::vector<std::string>& ungapped);
RcppExport SEXP _piglet_insert_gaps(SEXP gappedSEXP, SEXP ungappedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type gapped(gappedSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type ungapped(ungappedSEXP);
    rcpp_result_gen = Rcpp::wrap(insert_gaps(gapped, ungapped));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_piglet_allele_diff_strings", (DL_FUNC) &_piglet_allele_diff_strings, 3},
    {"_piglet_allele_diff_indices", (DL_FUNC) &_piglet_allele_diff_indices, 3},
    {"_piglet_allele_diff_paired", (DL_FUNC) &_piglet_allele_diff_paired, 5},
    {"_piglet_insert_gaps", (DL_FUNC) &_piglet_insert_gaps, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_piglet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
