// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// allele_diff_strings
std::vector<std::string> allele_diff_strings(std::vector<std::string> germs, int X);
RcppExport SEXP _piglet_allele_diff_strings(SEXP germsSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type germs(germsSEXP);
    Rcpp::traits::input_parameter< int >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(allele_diff_strings(germs, X));
    return rcpp_result_gen;
END_RCPP
}
// allele_diff_indices
std::vector<int> allele_diff_indices(std::vector<std::string> germs, int X);
RcppExport SEXP _piglet_allele_diff_indices(SEXP germsSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type germs(germsSEXP);
    Rcpp::traits::input_parameter< int >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(allele_diff_indices(germs, X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_piglet_allele_diff_strings", (DL_FUNC) &_piglet_allele_diff_strings, 2},
    {"_piglet_allele_diff_indices", (DL_FUNC) &_piglet_allele_diff_indices, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_piglet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
