# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Calculate differences between characters in columns of germs and return them as a string vector.
#'
#'@param germs A vector of strings representing germ sequences.
#'@param X The threshold index from which to return differences as strings.
#'@return A vector of strings containing differences between characters in columns.
#'
#' @examples
#' {
#' germs = c("ATCG", "ATCC") 
#' X = 3 
#' result = allele_diff_strings(germs, X) 
#' # "A2T", "T3C", "C2G"
#' }
#' 
#' @export
allele_diff_strings <- function(germs, X = 0L) {
    .Call(`_piglet_allele_diff_strings`, germs, X)
}

#'Calculate differences between characters in columns of germs and return their indices as an int vector.
#'
#'@param germs A vector of strings representing germ sequences.
#'@param X The threshold index from which to return differences as indices.
#'@return A vector of integers containing indices of differing columns.
#'
#' @examples 
#' 
#' {
#' germs = c("ATCG", "ATCC") 
#' X = 3 
#' result = allele_diff_indices(germs, X)
#' # 1, 2, 3
#' }
#' 
#' @export
allele_diff_indices <- function(germs, X = 0L) {
    .Call(`_piglet_allele_diff_indices`, germs, X)
}

