# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate differences between characters in columns of germs and return them as a string vector.
#'
#' @param germs A vector of strings representing germ sequences.
#' @param X The threshold index from which to return differences as strings.
#' @param non_mismatch_chars_nullable A set of characters that are ignored when comparing sequences (default: 'N', '.', '-').
#' @return A vector of strings containing differences between characters in columns.
#'
#' @examples
#' germs = c("ATCG", "ATCC") 
#' X = 3 
#' result = allele_diff_strings(germs, X) 
#' # "A2T", "T3C", "C2G"
#' @name allele_diff_strings
#' @export
allele_diff_strings <- function(germs, X = 0L, non_mismatch_chars_nullable = NULL) {
    .Call(`_piglet_allele_diff_strings`, germs, X, non_mismatch_chars_nullable)
}

#' Calculate differences between characters in columns of germs and return their indices as an int vector.
#'
#' @param germs A vector of strings representing germ sequences.
#' @param X The threshold index from which to return differences as indices.
#' @param non_mismatch_chars_nullable A set of characters that are ignored when comparing sequences (default: 'N', '.', '-').
#' @return A vector of integers containing indices of differing columns.
#'
#' @examples 
#' germs = c("ATCG", "ATCC") 
#' X = 3 
#' result = allele_diff_indices(germs, X)
#' # 1, 2, 3
#' @name allele_diff_indices
#' @export
allele_diff_indices <- function(germs, X = 0L, non_mismatch_chars_nullable = NULL) {
    .Call(`_piglet_allele_diff_indices`, germs, X, non_mismatch_chars_nullable)
}

#' Count or locate SNPs between paired germline and input sequences
#'
#' Compares each germline sequence in \code{germs} against the input sequence at the
#' same position in \code{inputs}, and returns either the positions of the mismatches
#' or how many there are. The two vectors are paired element by element, which is what
#' distinguishes this from \code{\link{allele_diff_indices}}, where every sequence is
#' compared against the first.
#'
#' A position is ignored when \emph{either} sequence carries a non-mismatch character,
#' by default a gap or an ambiguous base (\code{N}, \code{.}, \code{-}). Sequences of
#' unequal length are padded to the longer with \code{N}, so the padded positions never
#' count as mismatches.
#'
#' @param germs A vector of strings representing germline sequences.
#' @param inputs A vector of strings representing input sequences, paired with
#'   \code{germs} element by element.
#' @param X The position from which mismatches are counted, zero-based (default 0).
#' @param return_count Return the number of mismatches per pair rather than their
#'   positions (default \code{FALSE}).
#' @param non_mismatch_chars_nullable Characters ignored on either side when comparing
#'   (default \code{N}, \code{.}, \code{-}).
#' @return A list of integer vectors of one-based positions when
#'   \code{return_count = FALSE}, or an integer vector of counts when \code{TRUE}.
#'
#' @examples
#' germs  <- c("ACGTACGT", "ACGTACGT")
#' inputs <- c("ACGTTCGT", "ACGTTCGA")
#'
#' allele_diff_paired(germs, inputs, return_count = TRUE)   # 1, 2
#' allele_diff_paired(germs, inputs)                        # list(5), c(5, 8)
#'
#' @name allele_diff_paired
#' @export
allele_diff_paired <- function(germs, inputs, X = 0L, return_count = FALSE, non_mismatch_chars_nullable = NULL) {
    .Call(`_piglet_allele_diff_paired`, germs, inputs, X, return_count, non_mismatch_chars_nullable)
}

#' Insert gaps into an ungapped sequence based on a gapped reference sequence.
#'
#' This function inserts gaps (e.g., \code{.} or \code{-}) into an ungapped sequence
#' (\code{ungapped}) to match the positions of gaps in a reference sequence
#' (\code{gapped}). It ensures that the aligned sequence has the same gap structure as
#' the reference. Vectorised over both arguments, which are paired element by element.
#'
#' @param gapped A vector of strings representing the reference sequences with gaps.
#' @param ungapped A vector of strings representing the sequences without gaps.
#' @return A vector of strings with gaps inserted to match the gapped reference.
#'
#' @examples
#' gapped <- c("caggtc..aact", "caggtc---aact")
#' ungapped <- c("caggtcaact", "caggtcaact")
#'
#' insert_gaps(gapped, ungapped)   # "caggtc..aact", "caggtc---aact"
#'
#' @name insert_gaps
#' @export
insert_gaps <- function(gapped, ungapped) {
    .Call(`_piglet_insert_gaps`, gapped, ungapped)
}

